### ISSUE TITLE
Flip in get_unbalanced and labels hard to understand

### ISSUE THREAD

**Issue by PierreColombo** [yanaiela/demog-text-removal#1]
Hello,
Thanks for your work :) this is amazing. 
We are working on a project close to your setting in get_unbalanced there is a flip for pos/neg if we compare with the previous method for unbalanced... Just for consitency.

When a file is named pos_neg : pos refers to the downstream task and neg to the protected attribute ?

Thanks :)

**Comment by yanaiela** [comment]
Hey,
Thanks for your interest!

Yeah, that's right. The first pos/neg assigns the main task label, whereas the last assigns the protected attribute.
I could have been more clear about that, sorry 😅.

**Comment by PierreColombo** [comment]
Cool :) many thanks for the super quick answer ^^
